name: Custom Action Example
on:
  push:
    branches: [ main, release, develop ]
  pull_request:
    branches: [ main, release, develop ]

jobs:
  build-app:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: npm run build

  test-app:
    name: Test
    runs-on: ubuntu-latest
    needs: [build-app]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: npm run test
